global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: 'batch-processing'
    honor_labels: true # ВАЖНО: сохраняет теги (labels), которые передало ваше приложение
    metrics_path: '/metrics' # Явное указание стандартного пути Pushgateway
    static_configs:
      - targets: [ 'pushgateway:9091' ] # Адрес самого Pushgateway
        labels:
          application: batch-processing